// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Greet(arg1:string):Promise<string>;

export function LoadLogFile():Promise<models.ForscanLogs>;

export function Test2():Promise<string>;
